### PR TITLE
Add Sonic Pi

### PR DESCRIPTION
**Pull request by daverees4**
Just thought I'd add my Sonic Pi version of the WMB back into the respository!

### CODE REVIEW

**Comment by jbum** [comment]
Awesome thanks!  Jim

**Comment by jbum** [comment]
Made an attempt to add a version that uses harmonics, but it looks like it's hard to do with current version of Sonic P1- there's no built-in freqToMidi function, and kind of hard to do those calculations manually without log().  Would be cleaner if there was a frequency version of play (like playf).

**Comment by daverees4** [comment]
You've got it! -

Math.log()

**Comment by daverees4** [comment]
So your plaf function would be:

define :playf do |freq|
  play 69+(12*Math.log((freq.to_f/440), 2))
end

**Comment by jbum** [comment]
Sweet - checked in a harmonic variation.  (Feel free to hit me up on email, btw...  jbum at jbum dot com)

**Comment by daverees4** [comment]
Nice! Just the sound I need to hear before going to bed!

**Pull request merged**
